version: '3.8'

services:
  login-server:
    build:
      context: https://github.com/Nraitschew/login.git
      dockerfile: Dockerfile
    container_name: anymize-login
    ports:
      - "7500:7500"
    environment:
      # Server Configuration
      - NODE_ENV=production
      - PORT=7500
      
      # NocoDB Configuration (REQUIRED - set in Elestio)
      - NOCODB_BASE=${NOCODB_BASE}
      - NOCODB_TOKEN=${NOCODB_TOKEN}
      
      # Webhook URLs (REQUIRED - set in Elestio)
      - EMAIL_WEBHOOK=${EMAIL_WEBHOOK}
      - SMS_WEBHOOK=${SMS_WEBHOOK}
      
      # Session Configuration
      - SESSION_SECRET=${SESSION_SECRET:-CHANGE-THIS-IN-PRODUCTION-USE-RANDOM-32-CHARS}
      
      # CORS Origins - All Anymize domains
      - ALLOWED_ORIGINS=https://anymize.ai,https://login.anymize.ai,https://explore.anymize.ai,https://chat.anymize.ai,https://www.anymize.ai
      
      # Default redirect after successful login
      - SUCCESS_REDIRECT=https://explore.anymize.ai
      
    restart: unless-stopped
    
    # Health check configuration
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7500/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
    # Resource limits (adjust based on your Elestio plan)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
          
    # Logging configuration
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        
    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp